name: CI

on:
  push:
    branches:
    - '**'
    paths-ignore:
    - 'docs/**'
    - '**.md'
    - '**/.*.yml'
    - '.vscode/**'
    tags-ignore:
    - '*'
  schedule:
    # we want to verify our SDKs on a constant schedule
    - cron: '0 0 * * *'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      with:
        persist-credentials: false

    - name: Set up Ruby
      uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # v1.300.0
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Run linter
      run: bundle exec rubocop

    - name: Run unit tests
      run: bundle exec rake test
      env:
        PC_API_KEY: ${{ secrets.PC_API_KEY }} # zizmor: ignore[secrets-outside-env]
